import { SurahSummary } from './types.ts';

export const ALL_SURAS: SurahSummary[] = [
  { n: 1, bn: 'আল ফাতিহা', mn: 'সূচনা', ar: 'الفاتحة', type: 'makki', ayat: 7, en: 'Al-Fatihah' },
  { n: 2, bn: 'আল বাকারা', mn: 'বকনা-বাছুর', ar: 'البقرة', type: 'madani', ayat: 286, en: 'Al-Baqarah' },
  { n: 3, bn: 'আলে ইমরান', mn: 'ইমরানের পরিবার', ar: 'آل عمران', type: 'madani', ayat: 200, en: 'Ali \'Imran' },
  { n: 4, bn: 'আন নিসা', mn: 'নারী', ar: 'النساء', type: 'madani', ayat: 176, en: 'An-Nisa' },
  { n: 5, bn: 'আল মায়িদাহ', mn: 'খাদ্য পরিবেশিত দস্তরখান', ar: 'المائدة', type: 'madani', ayat: 120, en: 'Al-Ma\'idah' },
  { n: 6, bn: 'আল আনআম', mn: 'গৃহপালিত পশু', ar: 'الأنعام', type: 'makki', ayat: 165, en: 'Al-An\'am' },
  { n: 7, bn: 'আল আরাফ', mn: 'উচু স্থানসমূহ', ar: 'الأعراف', type: 'makki', ayat: 206, en: 'Al-A\'raf' },
  { n: 8, bn: 'আল আনফাল', mn: 'যুদ্ধলব্ধ সম্পদ', ar: 'الأنفال', type: 'madani', ayat: 75, en: 'Al-Anfal' },
  { n: 9, bn: 'আত তাওবাহ', mn: 'অনুশোচনা', ar: 'التوبة', type: 'madani', ayat: 129, en: 'At-Tawbah' },
  { n: 10, bn: 'ইউনুস', mn: 'নবী ইউনুস (আঃ)', ar: 'يونس', type: 'makki', ayat: 109, en: 'Yunus' },
  { n: 11, bn: 'হুদ', mn: 'নবী হুদ (আঃ)', ar: 'هود', type: 'makki', ayat: 123, en: 'Hud' },
  { n: 12, bn: 'ইউসুফ', mn: 'নবী ইউসুফ (আঃ)', ar: 'يوسف', type: 'makki', ayat: 111, en: 'Yusuf' },
  { n: 13, bn: 'আর রাদ', mn: 'বজ্রপাত', ar: 'الرعد', type: 'madani', ayat: 43, en: 'Ar-Ra\'d' },
  { n: 14, bn: 'ইব্রাহীম', mn: 'নবী ইব্রাহীম (আঃ)', ar: 'إبراهيم', type: 'makki', ayat: 52, en: 'Ibrahim' },
  { n: 15, bn: 'আল হিজর', mn: 'পাথুরে পাহাড়', ar: 'الحجر', type: 'makki', ayat: 99, en: 'Al-Hijr' },
  { n: 16, bn: 'আন নাহল', mn: 'মৌমাছি', ar: 'النحل', type: 'makki', ayat: 128, en: 'An-Nahl' },
  { n: 17, bn: 'আল ইসরা', mn: 'রাত্রিকালীন ভ্রমণ', ar: 'الإسراء', type: 'makki', ayat: 111, en: 'Al-Isra' },
  { n: 18, bn: 'আল কাহফ', mn: 'গুহা', ar: 'الكهف', type: 'makki', ayat: 110, en: 'Al-Kahf' },
  { n: 19, bn: 'মারইয়াম', mn: 'মারইয়াম (আঃ)', ar: 'مريم', type: 'makki', ayat: 98, en: 'Maryam' },
  { n: 20, bn: 'ত্বা-হা', mn: 'ত্বা-হা', ar: 'طه', type: 'makki', ayat: 135, en: 'Ta-Ha' },
  { n: 21, bn: 'আল আম্বিয়া', mn: 'নবীগণ', ar: 'الأنبياء', type: 'makki', ayat: 112, en: 'Al-Anbiya' },
  { n: 22, bn: 'আল হজ্জ', mn: 'হজ্জ', ar: 'الحج', type: 'madani', ayat: 78, en: 'Al-Hajj' },
  { n: 23, bn: 'আল মুমিনুন', mn: 'বিশ্বাসীগণ', ar: 'المؤمنون', type: 'makki', ayat: 118, en: 'Al-Mu\'minun' },
  { n: 24, bn: 'আন নূর', mn: 'আলো', ar: 'النور', type: 'madani', ayat: 64, en: 'An-Nur' },
  { n: 25, bn: 'আল ফুরকান', mn: 'সত্য-মিথ্যার পার্থক্যকারী', ar: 'الفرقان', type: 'makki', ayat: 77, en: 'Al-Furqan' },
  { n: 26, bn: 'আশ শুআরা', mn: 'কবিগণ', ar: 'الشعراء', type: 'makki', ayat: 227, en: 'Ash-Shu\'ara' },
  { n: 27, bn: 'আন নামল', mn: 'পিঁপড়া', ar: 'النمل', type: 'makki', ayat: 93, en: 'An-Naml' },
  { n: 28, bn: 'আল কাসাস', mn: 'কাহিনীসমূহ', ar: 'القصص', type: 'makki', ayat: 88, en: 'Al-Qasas' },
  { n: 29, bn: 'আল আনকাবুত', mn: 'মাকড়সা', ar: 'العنكبুত', type: 'makki', ayat: 69, en: 'Al-\'Ankabut' },
  { n: 30, bn: 'আর রুম', mn: 'রোমানরা', ar: 'الروم', type: 'makki', ayat: 60, en: 'Ar-Rum' },
  { n: 31, bn: 'লুকমান', mn: 'লুকমান', ar: 'لقمان', type: 'makki', ayat: 34, en: 'Luqman' },
  { n: 32, bn: 'আস সাজদাহ', mn: 'সিজদা', ar: 'السجدة', type: 'makki', ayat: 30, en: 'As-Sajdah' },
  { n: 33, bn: 'আল আহযাব', mn: 'জোটবদ্ধ বাহিনী', ar: 'الأحزاب', type: 'madani', ayat: 73, en: 'Al-Ahzab' },
  { n: 34, bn: 'সাবা', mn: 'সাবার জনগোষ্ঠী', ar: 'سبأ', type: 'makki', ayat: 54, en: 'Saba' },
  { n: 35, bn: 'ফাতির', mn: 'সৃষ্টিকর্তা', ar: 'فاطر', type: 'makki', ayat: 45, en: 'Fatir' },
  { n: 36, bn: 'ইয়া-সীন', mn: 'ইয়া-সীন', ar: 'يس', type: 'makki', ayat: 83, en: 'Ya-Sin' },
  { n: 37, bn: 'আস সাফফাত', mn: 'সারিবদ্ধগণ', ar: 'الصافات', type: 'makki', ayat: 182, en: 'As-Saffat' },
  { n: 38, bn: 'সোয়াদ', mn: 'সোয়াদ', ar: 'ص', type: 'makki', ayat: 88, en: 'Sad' },
  { n: 39, bn: 'আয যুমার', mn: 'দলসমূহ', ar: 'الزمر', type: 'makki', ayat: 75, en: 'Az-Zumar' },
  { n: 40, bn: 'গাফির', mn: 'ক্ষমাশীল', ar: 'غافر', type: 'makki', ayat: 85, en: 'Ghafir' },
  { n: 41, bn: 'ফুস্সিলাত', mn: 'বিশদভাবে বিবৃত', ar: 'fصلت', type: 'makki', ayat: 54, en: 'Fussilat' },
  { n: 42, bn: 'আশ শুরা', mn: 'পরামর্শ', ar: 'الشورى', type: 'makki', ayat: 53, en: 'Ash-Shura' },
  { n: 43, bn: 'আয যুখরুফ', mn: 'সোনার অলংকার', ar: 'الزخرف', type: 'makki', ayat: 89, en: 'Az-Zukhruf' },
  { n: 44, bn: 'আদ দুখান', mn: 'ধোয়া', ar: 'الدخان', type: 'makki', ayat: 59, en: 'Ad-Dukhan' },
  { n: 45, bn: 'আল জাসিয়াহ', mn: 'নতজানু', ar: 'الجاثية', type: 'makki', ayat: 37, en: 'Al-Jathiyah' },
  { n: 46, bn: 'আল আহকাফ', mn: 'বালিয়াড়ি', ar: 'الأحقاف', type: 'makki', ayat: 35, en: 'Al-Ahqaf' },
  { n: 47, bn: 'মুহাম্মদ', mn: 'নবী মুহাম্মদ (সাঃ)', ar: 'محمد', type: 'madani', ayat: 38, en: 'Muhammad' },
  { n: 48, bn: 'আল ফাতহ', mn: 'বিজয়', ar: 'الفتح', type: 'madani', ayat: 29, en: 'Al-Fath' },
  { n: 49, bn: 'আল হুজুরাত', mn: 'কামরাসমূহ', ar: 'الحجرات', type: 'madani', ayat: 18, en: 'Al-Hujurat' },
  { n: 50, bn: 'কাফ', mn: 'কাফ', ar: 'ق', type: 'makki', ayat: 45, en: 'Qaf' },
  { n: 51, bn: 'আয যারিয়াত', mn: 'বিক্ষেপকারী বায়ু', ar: 'الذاريات', type: 'makki', ayat: 60, en: 'Adh-Dhariyat' },
  { n: 52, bn: 'আত তুর', mn: 'পর্বত', ar: 'الطور', type: 'makki', ayat: 49, en: 'At-Tur' },
  { n: 53, bn: 'আন নাজম', mn: 'তারা', ar: 'النجم', type: 'makki', ayat: 62, en: 'An-Najm' },
  { n: 54, bn: 'আল কামার', mn: 'চাঁদ', ar: 'القمر', type: 'makki', ayat: 55, en: 'Al-Qamar' },
  { n: 55, bn: 'আর রাহমান', mn: 'পরম করুণাময়', ar: 'الرحمن', type: 'madani', ayat: 78, en: 'Ar-Rahman' },
  { n: 56, bn: 'আল ওয়াকিয়াহ', mn: 'নিশ্চিত ঘটনা', ar: 'الواقعة', type: 'makki', ayat: 96, en: 'Al-Waqi\'ah' },
  { n: 57, bn: 'আল হাদীদ', mn: 'লোহা', ar: 'الحديد', type: 'madani', ayat: 29, en: 'Al-Hadid' },
  { n: 58, bn: 'আল মুজাদালাহ', mn: 'আবেদনকারিণী', ar: 'المجادلة', type: 'madani', ayat: 22, en: 'Al-Mujadilah' },
  { n: 59, bn: 'আল হাশর', mn: 'সমাবেশ', ar: 'الحشر', type: 'madani', ayat: 24, en: 'Al-Hashr' },
  { n: 60, bn: 'আল মুমতাহিনাহ', mn: 'পরীক্ষিতা নারী', ar: 'الممتحنة', type: 'madani', ayat: 13, en: 'Al-Mumtahanah' },
  { n: 61, bn: 'আস সফ', mn: 'সারিবদ্ধ সৈন্যদল', ar: 'الصف', type: 'madani', ayat: 14, en: 'As-Saff' },
  { n: 62, bn: 'আল জুমুআহ', mn: 'শুক্রবার', ar: 'الجمعة', type: 'madani', ayat: 11, en: 'Al-Jumu\'ah' },
  { n: 63, bn: 'আল মুনাফিকুন', mn: 'মুনাফিকরা', ar: 'المنافقون', type: 'madani', ayat: 11, en: 'Al-Munafiqun' },
  { n: 64, bn: 'আত তাগাবুন', mn: 'মোহমুক্তি', ar: 'التغابন', type: 'madani', ayat: 18, en: 'At-Taghabun' },
  { n: 65, bn: 'আত তালাক', mn: 'তালাক', ar: 'الطلاق', type: 'madani', ayat: 12, en: 'At-Talaq' },
  { n: 66, bn: 'আত তাহরীম', mn: 'নিষিদ্ধকরণ', ar: 'التحريم', type: 'madani', ayat: 12, en: 'At-Tahrim' },
  { n: 67, bn: 'আল মুলক', mn: 'রাজত্ব', ar: 'الملك', type: 'makki', ayat: 30, en: 'Al-Mulk' },
  { n: 68, bn: 'আল কালাম', mn: 'কলম', ar: 'القلم', type: 'makki', ayat: 52, en: 'Al-Qalam' },
  { n: 69, bn: 'আল হাককাহ', mn: 'অনিবার্য', ar: 'الحاقة', type: 'makki', ayat: 52, en: 'Al-Haqqah' },
  { n: 70, bn: 'আল মাআরিজ', mn: 'উর্ধ্বারোহণের সিঁড়ি', ar: 'المعارج', type: 'makki', ayat: 44, en: 'Al-Ma\'arij' },
  { n: 71, bn: 'নুহ', mn: 'নবী নুহ (আঃ)', ar: 'نوح', type: 'makki', ayat: 28, en: 'Nuh' },
  { n: 72, bn: 'আল জিন', mn: 'জিন', ar: 'الجن', type: 'makki', ayat: 28, en: 'Al-Jinn' },
  { n: 73, bn: 'আল মুযযাম্মিল', mn: 'চাদরাবৃত', ar: 'المزمل', type: 'makki', ayat: 20, en: 'Al-Muzzammil' },
  { n: 74, bn: 'আল মুদ্দাস্সির', mn: 'বস্ত্রাবৃত', ar: 'المدثر', type: 'makki', ayat: 56, en: 'Al-Muddaththir' },
  { n: 75, bn: 'আল কিয়ামাহ', mn: 'পুনরুত্থান', ar: 'القيامة', type: 'makki', ayat: 40, en: 'Al-Qiyamah' },
  { n: 76, bn: 'আল ইনসান', mn: 'মানুষ', ar: 'الإنسان', type: 'madani', ayat: 31, en: 'Al-Insan' },
  { n: 77, bn: 'আল মুরসালাত', mn: 'প্রেরিতগণ', ar: 'المرسلات', type: 'makki', ayat: 50, en: 'Al-Mursalat' },
  { n: 78, bn: 'আন নাবা', mn: 'মহাসংবাদ', ar: 'النبأ', type: 'makki', ayat: 40, en: 'An-Naba' },
  { n: 79, bn: 'আন নাযিআত', mn: 'আকর্ষণকারীগণ', ar: 'النازعات', type: 'makki', ayat: 46, en: 'An-Nazi\'at' },
  { n: 80, bn: 'আবাসা', mn: 'তিনি ভ্রুকুটি করলেন', ar: 'عبس', type: 'makki', ayat: 42, en: 'Abasa' },
  { n: 81, bn: 'আত তাকভীর', mn: 'অন্ধকারাচ্ছন্নতা', ar: 'التكوير', type: 'makki', ayat: 29, en: 'At-Takwir' },
  { n: 82, bn: 'আল ইনফিতার', mn: 'বিদীর্ণ হওয়া', ar: 'الانفطار', type: 'makki', ayat: 19, en: 'Al-Infitar' },
  { n: 83, bn: 'আল মুতাফফিফীন', mn: 'মাপে কম দেয় যারা', ar: 'المطففين', type: 'makki', ayat: 36, en: 'Al-Mutaffifin' },
  { n: 84, bn: 'আল ইনশিকাক', mn: 'বিচ্ছিন্ন হওয়া', ar: 'الانشقاق', type: 'makki', ayat: 25, en: 'Al-Inshiqaq' },
  { n: 85, bn: 'আল বুরুজ', mn: 'রাশিচক্র', ar: 'البروج', type: 'makki', ayat: 22, en: 'Al-Buruj' },
  { n: 86, bn: 'আত তারিক', mn: 'রাতের আগমনকারী', ar: 'الطارق', type: 'makki', ayat: 17, en: 'At-Tariq' },
  { n: 87, bn: 'আল আলা', mn: 'সর্বোচ্চ', ar: 'الأعلى', type: 'makki', ayat: 19, en: 'Al-A\'la' },
  { n: 88, bn: 'আল গাশিয়াহ', mn: 'অভিভূতকারী ঘটনা', ar: 'الغاشية', type: 'makki', ayat: 26, en: 'Al-Ghashiyah' },
  { n: 89, bn: 'আল ফজর', mn: 'ভোর', ar: 'الفجر', type: 'makki', ayat: 30, en: 'Al-Fajr' },
  { n: 90, bn: 'আল বালাদ', mn: 'নগর', ar: 'البلد', type: 'makki', ayat: 20, en: 'Al-Balad' },
  { n: 91, bn: 'আশ শামস', mn: 'সূর্য', ar: 'الشمس', type: 'makki', ayat: 15, en: 'Ash-Shams' },
  { n: 92, bn: 'আল লাইল', mn: 'রাত', ar: 'الليل', type: 'makki', ayat: 21, en: 'Al-Layl' },
  { n: 93, bn: 'আদ দুহা', mn: 'পূর্বাহ্ন', ar: 'الضحى', type: 'makki', ayat: 11, en: 'Ad-Duha' },
  { n: 94, bn: 'আশ শারহ', mn: 'বক্ষ উন্মোচন', ar: 'الشرح', type: 'makki', ayat: 8, en: 'Ash-Sharh' },
  { n: 95, bn: 'আত তীন', mn: 'ডুমুর', ar: 'التين', type: 'makki', ayat: 8, en: 'At-Tin' },
  { n: 96, bn: 'আল আলাক', mn: 'জমাট রক্ত', ar: 'العلق', type: 'makki', ayat: 19, en: 'Al-\'Alaq' },
  { n: 97, bn: 'আল কদর', mn: 'মহিমান্বিত রাত', ar: 'القدر', type: 'makki', ayat: 5, en: 'Al-Qadr' },
  { n: 98, bn: 'আল বাইয়্যিনাহ', mn: 'সুস্পষ্ট প্রমাণ', ar: 'البينة', type: 'madani', ayat: 8, en: 'Al-Bayyinah' },
  { n: 99, bn: 'আয যিলযাল', mn: 'ভূমিকম্প', ar: 'الزلزلة', type: 'madani', ayat: 8, en: 'Az-Zalzalah' },
  { n: 100, bn: 'আল আদিয়াত', mn: 'দৌড়ন্ত অশ্বসমূহ', ar: 'العاديات', type: 'makki', ayat: 11, en: 'Al-\'Adiyat' },
  { n: 101, bn: 'আল কারিয়াহ', mn: 'মহাবিপর্যয়', ar: 'القارعة', type: 'makki', ayat: 11, en: 'Al-Qari\'ah' },
  { n: 102, bn: 'আত তাকাসুর', mn: 'প্রাচুর্যের প্রতিযোগিতা', ar: 'التكاثر', type: 'makki', ayat: 8, en: 'At-Takathur' },
  { n: 103, bn: 'আল আসর', mn: 'সময়', ar: 'العصر', type: 'makki', ayat: 3, en: 'Al-\'Asr' },
  { n: 104, bn: 'আল হুমাযাহ', mn: 'পরচর্চাকারী', ar: 'الهمزة', type: 'makki', ayat: 9, en: 'Al-Humazah' },
  { n: 105, bn: 'আল ফীল', mn: 'হাতি', ar: 'الفيل', type: 'makki', ayat: 5, en: 'Al-Fil' },
  { n: 106, bn: 'কুরাইশ', mn: 'কুরাইশ গোত্র', ar: 'قريش', type: 'makki', ayat: 4, en: 'Quraysh' },
  { n: 107, bn: 'আল মাউন', mn: 'সামান্য সাহায্য', ar: 'الماعون', type: 'makki', ayat: 7, en: 'Al-Ma\'un' },
  { n: 108, bn: 'আল কাউসার', mn: 'কাউসার', ar: 'الكوثر', type: 'makki', ayat: 3, en: 'Al-Kawthar' },
  { n: 109, bn: 'আল কাফিরুন', mn: 'অবিশ্বাসীগণ', ar: 'الكافرون', type: 'makki', ayat: 6, en: 'Al-Kafirun' },
  { n: 110, bn: 'আন নাসর', mn: 'সাহায্য', ar: 'النصر', type: 'madani', ayat: 3, en: 'An-Nasr' },
  { n: 111, bn: 'আল মাসাদ', mn: 'খেজুরের ছড়া', ar: 'المسد', type: 'makki', ayat: 5, en: 'Al-Masad' },
  { n: 112, bn: 'আল ইখলাস', mn: 'একনিষ্ঠতা', ar: 'الإخلاص', type: 'makki', ayat: 4, en: 'Al-Ikhlas' },
  { n: 113, bn: 'আল ফালাক', mn: 'ভোরের আলো', ar: 'الفلق', type: 'makki', ayat: 5, en: 'Al-Falaq' },
  { n: 114, bn: 'আন নাস', mn: 'মানবজাতি', ar: 'الناس', type: 'makki', ayat: 6, en: 'An-Nas' }
];
